version: '3.8'
services:
  emucomp:
    container_name: emucomp
    image: emucomp:latest
    networks:
      - emucomp
  nginx:
    container_name: emucomp-nginx
    image: nginx
    ports:
      - "8080:8080"
    environment:
      - EMIL_IMAGE_PATH=/data/emil
      - EMIL_EMULATOR_REPO_PATH=${EMIL_IMAGE_PATH}/emulator-repository/images
      - EMIL_ENV_REPO_PATH=${EMIL_IMAGE_PATH}/environment-repository/images
      - EMIL_ROM_REPO_PATH=${EMIL_IMAGE_PATH}/environment-repository/roms
      - EMIL_CHECKPOINT_REPO_PATH=${EMIL_IMAGE_PATH}/environment-repository/checkpoints
      - EMIL_OBJECT_REPO_PATH=${EMIL_IMAGE_PATH}/object-repository/archives
      - EMIL_COMPONENT_REPO_PATH=${EMIL_IMAGE_PATH}/components
    volumes:
      - ./data:/data
      - ./nginx-template.conf:/etc/nginx/nginx.conf
    networks:
      - emucomp
networks:
  emucomp: