version: '3.8'
services:
  emucomp:
    container_name: emucomp
    image: emucomp:latest
    networks:
      - emucomp
  nginx:
    container_name: emucomp-nginx
    image: nginx
    ports:
      - "8080:8080"
    environment:
      - EMIL_IMAGE_PATH=/data
      - EMIL_EMULATOR_REPO_PATH=${EMIL_IMAGE_PATH}/emulators/qemu-system-v31.qcow2
      - EMIL_IMAGE=${EMIL_IMAGE_PATH}/image/windows-for-workgroups-311-base-v2.qcow2
      - EMIL_OBJ=${EMIL_IMAGE_PATH}/objects/
    volumes:
      - /home/emu:/data
      - ./nginx-template.conf:/etc/nginx/nginx.conf
    networks:
      - emucomp
networks:
  emucomp: