version: '3.8'
services:
  emucomp:
    container_name: emucomp
    image: emucomp:latest
    ports:
      - "8080:8080"
    networks:
      - emucomp
#  nginx:
#    container_name: emucomp-nginx
#    image: nginx
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./test-configuration.conf:/etc/nginx/nginx.conf
#    networks:
#      - emucomp
networks:
  emucomp: