quarkus:
  application:
    name: emucomp-api
  arc:
    include-dependencies: true
  config:
    locations:
      - default.yml
      - blob-default.yml
      - connection.yml
      - threads.yml
  grpc:
    server:
      health:
        enabled: true
      host: 0.0.0.0