quarkus:
  application:
    name: emucomp-api
  config:
    locations:
      - default.yml
      - blob-default.yml
      - connection.yml
      - threads.yml
      - commons.yml
  grpc:
    server:
      health:
        enabled: true
      host: 0.0.0.0
      port: 9000