components:
  client_timeout: 45s
  warmup_timeout: 180s
  timeout: 60s
  binary:
    qemu: /usr/bin/qemu-system-
    basilisk: /usr/bin/BasiliskII
    sheepshaver:  /usr/bin/SheepShaver
    dosbox: /usr/bin/dosbox
    hatari: /usr/bin/hatari
    kegs: /usr/bin/kegs
    beebem: /usr/bin/beebem
    vbox:
      headlessexec: /usr/bin/VBoxSDL
      manageexec:  /usr/bin/VBoxManage
    vice:
      c64:  /usr/bin/x64
      c128: /usr/bin/x128
    pce:
      atarist:  /usr/bin/pce-atarist
      ibmpc:  /usr/bin/pce-ibmpc
      macplus:  /usr/bin/pce-macplus
    vdeswitch:  /usr/bin/vde_switch
    vdeslirp: /usr/bin/slirpvde
    nodetcprunner: /libexec/vdenode
    nodetcpscript: /libexec/picotcp/webemulator/webemulator/vdenode.js

    runc: runc
    vdeplug: /usr/bin/vde_plug
  xpra:
    ports: 7000-7100
    enable_gpu: false

  vice_defaults_dir: /home/bwfla/server-data/vice-defaults

  emulator_containers:
    enabled: false
    snapshot: false
    uid: 1000
    gid: 1000

  containers:
    blobstore: http://eaas:8080
    usernamespace:
      enabled: false
      user: bwfla
      group: bwfla

  session_statistics:
    flush_delay: 30s
  tcpNode:
    ports: 10000-10010

emucomp:
  blobstore_soap: http://eaas:8080
  inactivitytimeout:  0
  enable_pulseaudio: false
  enable_screenshooter: false
  debug_bean_enabled: false
  libfaketime: /usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
  curl_proxy: /usr/local/lib/LD_PRELOAD_libcurl.so
  rompath: /eaas/roms
  alsa_card: PCH

rest:
  blobstore: http://eaas:8080/blobstore/api/v1/blobs
  imagearchive: http://eaas:8080/image-archive

emil:
  cachedclassificationpath: /home/bwfla/classification-cache/
  exportpath: /home/bwfla/export/
  emilenvironmentspath: /home/bwfla/emil-environments/
  inputpathtodelete: /tmp/toDelete/
  dockerTmpBuildFiles: /tmp/docker-tmp-build-files/
  classificationservice: http://eaas:8080/
  imageproposerservice: http://eaas:8080
  emilobjectenvironmentspaths: /home/bwfla/emil-object-environments/
  usersessionretention: 10080
  containerdata:
    imagebuilder:
      timeout: 30 mins
      delay: 3 secs
  imagesDatabase: images
  emilDatabase: emil
  classificationDatabase: classification
  max_session_duration: 0 sec
  autorun_scripts_dir: /home/bwfla/server-data/autorun-scripts
  default_environments_path: /home/bwfla/server-data/default-environments.properties

ws:
  blobstore: http://eaas:8080/
  imagebuilder: http://eaas:8080/
  imagearchive: http://eaas:8080/
  eaasgw:  http://eaas:8080/
  embedgw: http://eaas:8080/
  objectarchive: http://eaas:8080/
  softwarearchive: http://eaas:8080/

metadata_repositories:
  - name: public-images
    type: images
    mode: R
  - name: public-environments
    type: environments
    mode: R
  - name: public-software
    type: software
    mode: R
  - name: remote-images
    type: images
    mode: W
  - name: remote-environments
    type: environments
    mode: W
  - name: remote-software
    type: software
    mode: W
