apiVersion: v1
kind: Service
metadata:
  name: emucomp-service
spec:
  type: ClusterIP
  selector:
    app: emucomp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP